{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2f43d9c5-8f43-4fe5-9522-4075182587d2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f8ade2d5-9db4-4ca8-96f3-a6ac1b0fc4b3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# IMPOER LIBRARIES\n",
    "import pandas as pd \n",
    "import numpy as np \n",
    "import matplotlib.pyplot as plt \n",
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "f723af2a-ddda-4481-9355-0e5e24926101",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.express as px"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "170df132-735a-4335-883b-67ab2e4b4454",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load Data\n",
    "df = pd.read_csv(r\"C:\\united_inteship\\Un_project\\Thales_Group_Manufacturing01.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "e6d69e8e-33fa-4bdf-b0fd-11c5f19e81fa",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Date</th>\n",
       "      <th>Timestamp</th>\n",
       "      <th>Machine_ID</th>\n",
       "      <th>Operation_Mode</th>\n",
       "      <th>Temperature_C</th>\n",
       "      <th>Vibration_Hz</th>\n",
       "      <th>Power_Consumption_kW</th>\n",
       "      <th>Network_Latency_ms</th>\n",
       "      <th>Packet_Loss</th>\n",
       "      <th>Quality_Control_Defect_Rate</th>\n",
       "      <th>Production_Speed_units_per_hr</th>\n",
       "      <th>Predictive_Maintenance_Score</th>\n",
       "      <th>Error_Rate</th>\n",
       "      <th>Efficiency_Status</th>\n",
       "      <th>Month</th>\n",
       "      <th>Month_Name</th>\n",
       "      <th>Hour</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>01-01-2025</td>\n",
       "      <td>00:00:00</td>\n",
       "      <td>39</td>\n",
       "      <td>Idle</td>\n",
       "      <td>74.138</td>\n",
       "      <td>3.501</td>\n",
       "      <td>8.612</td>\n",
       "      <td>10.651</td>\n",
       "      <td>0.208</td>\n",
       "      <td>7.751</td>\n",
       "      <td>477.657</td>\n",
       "      <td>0.345</td>\n",
       "      <td>14.965</td>\n",
       "      <td>Low</td>\n",
       "      <td>1</td>\n",
       "      <td>January</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>01-01-2025</td>\n",
       "      <td>00:01:00</td>\n",
       "      <td>29</td>\n",
       "      <td>Active</td>\n",
       "      <td>84.265</td>\n",
       "      <td>3.356</td>\n",
       "      <td>2.269</td>\n",
       "      <td>29.112</td>\n",
       "      <td>2.228</td>\n",
       "      <td>4.989</td>\n",
       "      <td>398.175</td>\n",
       "      <td>0.770</td>\n",
       "      <td>7.678</td>\n",
       "      <td>Low</td>\n",
       "      <td>1</td>\n",
       "      <td>January</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>01-01-2025</td>\n",
       "      <td>00:02:00</td>\n",
       "      <td>15</td>\n",
       "      <td>Active</td>\n",
       "      <td>44.280</td>\n",
       "      <td>2.080</td>\n",
       "      <td>6.144</td>\n",
       "      <td>18.357</td>\n",
       "      <td>1.639</td>\n",
       "      <td>0.457</td>\n",
       "      <td>108.075</td>\n",
       "      <td>0.987</td>\n",
       "      <td>8.198</td>\n",
       "      <td>Low</td>\n",
       "      <td>1</td>\n",
       "      <td>January</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>01-01-2025</td>\n",
       "      <td>00:03:00</td>\n",
       "      <td>43</td>\n",
       "      <td>Active</td>\n",
       "      <td>40.569</td>\n",
       "      <td>0.298</td>\n",
       "      <td>4.068</td>\n",
       "      <td>29.154</td>\n",
       "      <td>1.161</td>\n",
       "      <td>4.583</td>\n",
       "      <td>329.579</td>\n",
       "      <td>0.983</td>\n",
       "      <td>2.741</td>\n",
       "      <td>Medium</td>\n",
       "      <td>1</td>\n",
       "      <td>January</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>01-01-2025</td>\n",
       "      <td>00:04:00</td>\n",
       "      <td>8</td>\n",
       "      <td>Idle</td>\n",
       "      <td>75.064</td>\n",
       "      <td>0.346</td>\n",
       "      <td>6.226</td>\n",
       "      <td>34.029</td>\n",
       "      <td>4.797</td>\n",
       "      <td>2.288</td>\n",
       "      <td>159.114</td>\n",
       "      <td>0.573</td>\n",
       "      <td>12.101</td>\n",
       "      <td>Low</td>\n",
       "      <td>1</td>\n",
       "      <td>January</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         Date Timestamp  Machine_ID Operation_Mode  Temperature_C  \\\n",
       "0  01-01-2025  00:00:00          39           Idle         74.138   \n",
       "1  01-01-2025  00:01:00          29         Active         84.265   \n",
       "2  01-01-2025  00:02:00          15         Active         44.280   \n",
       "3  01-01-2025  00:03:00          43         Active         40.569   \n",
       "4  01-01-2025  00:04:00           8           Idle         75.064   \n",
       "\n",
       "   Vibration_Hz  Power_Consumption_kW  Network_Latency_ms  Packet_Loss  \\\n",
       "0         3.501                 8.612              10.651        0.208   \n",
       "1         3.356                 2.269              29.112        2.228   \n",
       "2         2.080                 6.144              18.357        1.639   \n",
       "3         0.298                 4.068              29.154        1.161   \n",
       "4         0.346                 6.226              34.029        4.797   \n",
       "\n",
       "   Quality_Control_Defect_Rate  Production_Speed_units_per_hr  \\\n",
       "0                        7.751                        477.657   \n",
       "1                        4.989                        398.175   \n",
       "2                        0.457                        108.075   \n",
       "3                        4.583                        329.579   \n",
       "4                        2.288                        159.114   \n",
       "\n",
       "   Predictive_Maintenance_Score  Error_Rate Efficiency_Status  Month  \\\n",
       "0                         0.345      14.965               Low      1   \n",
       "1                         0.770       7.678               Low      1   \n",
       "2                         0.987       8.198               Low      1   \n",
       "3                         0.983       2.741            Medium      1   \n",
       "4                         0.573      12.101               Low      1   \n",
       "\n",
       "  Month_Name  Hour  \n",
       "0    January     0  \n",
       "1    January     0  \n",
       "2    January     0  \n",
       "3    January     0  \n",
       "4    January     0  "
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5a82e662-04ee-4bcd-b380-8949b057650d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "37fb540d-4d28-4f1c-b864-95b5afdbe979",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.express as px\n",
    "\n",
    "# -----------------------------\n",
    "# PAGE CONFIG\n",
    "# -----------------------------\n",
    "st.set_page_config(page_title=\"6G Network Dashboard\", layout=\"wide\")\n",
    "\n",
    "st.title(\"📡 6G Network Performance Analysis\")\n",
    "st.markdown(\"Smart Manufacturing | Advanced Analytics Dashboard\")\n",
    "\n",
    "# -----------------------------\n",
    "# LOAD DATA\n",
    "# -----------------------------\n",
    "df = pd.read_csv(r\"C:\\united_inteship\\Un_project\\Thales_Group_Manufacturing01.csv\")\n",
    "\n",
    "# -----------------------------\n",
    "# DATA PREPROCESSING\n",
    "# -----------------------------\n",
    "# Risk Category\n",
    "def risk_category(row):\n",
    "    if row[\"Network_Latency_ms\"] > 30 or row[\"Packet_Loss\"] > 5:\n",
    "        return \"Critical\"\n",
    "    elif row[\"Network_Latency_ms\"] > 15:\n",
    "        return \"Warning\"\n",
    "    else:\n",
    "        return \"Normal\"\n",
    "\n",
    "df[\"Risk_Level\"] = df.apply(risk_category, axis=1)\n",
    "\n",
    "# -----------------------------\n",
    "# SIDEBAR FILTERS\n",
    "# -----------------------------\n",
    "st.sidebar.header(\"🔍 Filters\")\n",
    "\n",
    "operation_mode = st.sidebar.multiselect(\n",
    "    \"Operation Mode\",\n",
    "    df[\"Operation_Mode\"].unique(),\n",
    "    default=df[\"Operation_Mode\"].unique()\n",
    ")\n",
    "\n",
    "efficiency = st.sidebar.multiselect(\n",
    "    \"Efficiency Status\",\n",
    "    df[\"Efficiency_Status\"].unique(),\n",
    "    default=df[\"Efficiency_Status\"].unique()\n",
    ")\n",
    "\n",
    "risk = st.sidebar.multiselect(\n",
    "    \"Risk Level\",\n",
    "    df[\"Risk_Level\"].unique(),\n",
    "    default=df[\"Risk_Level\"].unique()\n",
    ")\n",
    "\n",
    "df_filtered = df[\n",
    "    (df[\"Operation_Mode\"].isin(operation_mode)) &\n",
    "    (df[\"Efficiency_Status\"].isin(efficiency)) &\n",
    "    (df[\"Risk_Level\"].isin(risk))\n",
    "]\n",
    "\n",
    "# -----------------------------\n",
    "# KPI SECTION\n",
    "# -----------------------------\n",
    "st.subheader(\"📊 Key Performance Indicators\")\n",
    "\n",
    "col1, col2, col3, col4 = st.columns(4)\n",
    "\n",
    "col1.metric(\"Avg Latency (ms)\", round(df_filtered[\"Network_Latency_ms\"].mean(), 2))\n",
    "col2.metric(\"Avg Packet Loss (%)\", round(df_filtered[\"Packet_Loss\"].mean(), 2))\n",
    "col3.metric(\"Avg Production Speed\", round(df_filtered[\"Production_Speed_units_per_hr\"].mean(), 2))\n",
    "col4.metric(\"Avg Error Rate (%)\", round(df_filtered[\"Error_Rate\"].mean(), 2))\n",
    "\n",
    "# -----------------------------\n",
    "# RISK DISTRIBUTION\n",
    "# -----------------------------\n",
    "st.subheader(\"🚨 Network Risk Distribution\")\n",
    "\n",
    "risk_count = df_filtered[\"Risk_Level\"].value_counts().reset_index()\n",
    "risk_count.columns = [\"Risk_Level\", \"Count\"]\n",
    "\n",
    "fig_risk = px.pie(\n",
    "    risk_count,\n",
    "    names=\"Risk_Level\",\n",
    "    values=\"Count\",\n",
    "    title=\"Risk Level Distribution\"\n",
    ")\n",
    "st.plotly_chart(fig_risk, use_container_width=True)\n",
    "\n",
    "# -----------------------------\n",
    "# LATENCY vs SPEED\n",
    "# -----------------------------\n",
    "col5, col6 = st.columns(2)\n",
    "\n",
    "with col5:\n",
    "    st.subheader(\"📈 Latency vs Production Speed\")\n",
    "    fig1 = px.scatter(\n",
    "        df_filtered,\n",
    "        x=\"Network_Latency_ms\",\n",
    "        y=\"Production_Speed_units_per_hr\",\n",
    "        color=\"Efficiency_Status\"\n",
    "    )\n",
    "    st.plotly_chart(fig1, use_container_width=True)\n",
    "\n",
    "with col6:\n",
    "    st.subheader(\"📉 Packet Loss vs Error Rate\")\n",
    "    fig2 = px.scatter(\n",
    "        df_filtered,\n",
    "        x=\"Packet_Loss\",\n",
    "        y=\"Error_Rate\",\n",
    "        color=\"Risk_Level\"\n",
    "    )\n",
    "    st.plotly_chart(fig2, use_container_width=True)\n",
    "\n",
    "# -----------------------------\n",
    "# EFFICIENCY ANALYSIS\n",
    "# -----------------------------\n",
    "col7, col8 = st.columns(2)\n",
    "\n",
    "with col7:\n",
    "    st.subheader(\"📊 Efficiency Distribution\")\n",
    "    fig3 = px.histogram(\n",
    "        df_filtered,\n",
    "        x=\"Efficiency_Status\",\n",
    "        color=\"Efficiency_Status\"\n",
    "    )\n",
    "    st.plotly_chart(fig3, use_container_width=True)\n",
    "\n",
    "with col8:\n",
    "    st.subheader(\"⚙️ Operation Mode Impact\")\n",
    "    fig4 = px.box(\n",
    "        df_filtered,\n",
    "        x=\"Operation_Mode\",\n",
    "        y=\"Production_Speed_units_per_hr\",\n",
    "        color=\"Operation_Mode\"\n",
    "    )\n",
    "    st.plotly_chart(fig4, use_container_width=True)\n",
    "\n",
    "# -----------------------------\n",
    "# HEATMAP\n",
    "# -----------------------------\n",
    "st.subheader(\"🔥 Correlation Heatmap\")\n",
    "\n",
    "corr = df_filtered.select_dtypes(include=np.number).corr()\n",
    "\n",
    "fig5 = px.imshow(corr, text_auto=True)\n",
    "st.plotly_chart(fig5, use_container_width=True)\n",
    "\n",
    "# -----------------------------\n",
    "# TIME TREND (ADVANCED)\n",
    "# -----------------------------\n",
    "# -----------------------------\n",
    "# TIME TREND (ADVANCED)\n",
    "# -----------------------------\n",
    "st.subheader(\"📅 Network Latency Trend\")\n",
    "\n",
    "df[\"Date\"] = pd.to_datetime(df[\"Date\"], dayfirst=True, errors='coerce')\n",
    "df = df.dropna(subset=[\"Date\"])\n",
    "\n",
    "trend = df.groupby(\"Date\")[\"Network_Latency_ms\"].mean().reset_index()\n",
    "\n",
    "fig6 = px.line(trend, x=\"Date\", y=\"Network_Latency_ms\")\n",
    "st.plotly_chart(fig6, use_container_width=True)\n",
    "\n",
    "# -----------------------------\n",
    "# FOOTER\n",
    "# -----------------------------\n",
    "st.success(\"✅ Advanced Dashboard Loaded Successfully\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8a89e727-658e-4fe3-8684-3d2b7de27699",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2a39e56a-a73b-4feb-85b2-4602f426f80d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0e17d252-c24a-4b94-93c7-5283c52ff228",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8e9c5e40-8eb7-4846-be9f-e6b535f6ca07",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c5d392b1-9728-433a-92a6-6a318c3e1a26",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f4f32886-31fc-4c74-8c15-dc10c59d8d5e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "06f56c16-a57d-4f8f-acf8-32b2cdc08eed",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4ffab9fc-66b4-4ac1-8701-da910b5e7acd",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "00091d86-843f-4a1a-bb42-9670250a756a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7e0a8a47-40e9-4c5a-b60a-fbfe4a437f93",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e577ecab-ec24-46ff-9c42-a93d67047ff3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a1038d20-678b-4c91-966a-36578c52e7a7",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9efd5bdd-3f4b-4891-8b60-5486d9801221",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dc6fbc47-8d36-4523-851f-066ae9a8a098",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a7cd7d33-66ce-4ffb-9507-d7b9f5c0192b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "caaa7d7b-e32e-4ba4-bf24-ad9550b5207d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8e5952ad-837f-44c5-9f73-8427b6676ffc",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "78c86bb1-cde8-48ac-97e4-8d90d3479777",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d4971d70-26d8-4a55-a2c5-2b3e3e761af0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "59c803ce-5280-429c-b5b7-d07640ff5e61",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
